use Distribuidora_v2
INSERT INTO Productos (nombre, unidad, fecha_registro, estado, categoria, proveedor, precio, stock, borrado) 
		VALUES('Peperina', NULL, NULL, NULL, NULL, NULL, 643.54, 150, 0)
INSERT INTO Productos (nombre, unidad, fecha_registro, estado, categoria, proveedor, precio, stock, borrado) 
		VALUES('Poleo', NULL, NULL, NULL, NULL, NULL, 339.93, 250, 0)
INSERT INTO Productos (nombre, unidad, fecha_registro, estado, categoria, proveedor, precio, stock, borrado) 
		VALUES('Palo Amarillo', NULL, NULL, NULL, NULL, NULL, 189.50, 45, 0)
INSERT INTO Productos (nombre, unidad, fecha_registro, estado, categoria, proveedor, precio, stock, borrado) 
		VALUES('Jarilla', NULL, NULL, NULL, NULL, NULL, 175.90, 95, 0)
INSERT INTO Productos (nombre, unidad, fecha_registro, estado, categoria, proveedor, precio, stock, borrado) 
		VALUES('Incayuyo', NULL, NULL, NULL, NULL, NULL, 542.57, 120, 0)
INSERT INTO Productos (nombre, unidad, fecha_registro, estado, categoria, proveedor, precio, stock, borrado) 
		VALUES('Té de Burro', NULL, NULL, NULL, NULL, NULL, 242.56, 145, 0)
